// Per-server PHP website hosting on the shared cs-php (Apache + PHP) container.
//
// Layout on the php-www volume (mounted at /var/www/html inside cs-php):
//   servers/<port>/          public web root of one site (customer files)
//   .sites-data/<port>/      private data: config.php, sessions, tmp
//   .panel/domains.map       custom domain -> port map read by Apache
// Isolation (open_basedir per site, disabled shell functions, no .user.ini,
// panel cookie stripped) is enforced by php/panel-prepend.php + php/*.conf.
const fs = require('fs');
const path = require('path');
const cfg = require('./config');
const panelDb = require('./panelDb');

const WWW = cfg.php.wwwPath;
const SITES_DIR = 'servers';
const DATA_DIR = '.sites-data';
const PANEL_DIR = '.panel';
const TEMPLATES_ROOT = path.join(__dirname, 'php-templates');

const TEMPLATES = [
    { id: 'community', name: 'Topluluk Sitesi', description: 'Canlı sunucu durumu, oyuncu listesi, "Bağlan" butonu ve MySQL istatistik tablosu içeren hazır site.' },
    { id: 'blank', name: 'Boş Başlangıç', description: 'Veritabanı bağlantı örneği içeren minimal index.php.' }
];

function httpError(status, message) {
    const err = new Error(message);
    err.statusCode = status;
    return err;
}

function resolveInside(base, rel = '') {
    const resolvedBase = path.resolve(base);
    const resolved = path.resolve(resolvedBase, rel);
    if (resolved !== resolvedBase && !resolved.startsWith(resolvedBase + path.sep)) {
        throw httpError(403, 'Access denied');
    }
    return resolved;
}

function portOf(record) {
    const port = parseInt(record && record.port, 10);
    if (!Number.isInteger(port) || port <= 0) throw httpError(400, 'Invalid server port');
    return port;
}

function siteDir(record) {
    return resolveInside(path.join(WWW, SITES_DIR), String(portOf(record)));
}

function dataDir(record) {
    return resolveInside(path.join(WWW, DATA_DIR), String(portOf(record)));
}

function chownTree(target) {
    if (process.getuid && process.getuid() !== 0) return; // only root can chown
    const { fileUid, fileGid } = cfg.php;
    const walk = p => {
        let stat;
        try { stat = fs.lstatSync(p); } catch (_) { return; }
        if (stat.isSymbolicLink()) return;
        try { fs.lchownSync(p, fileUid, fileGid); } catch (_) { /* ignore */ }
        if (stat.isDirectory()) fs.readdirSync(p).forEach(name => walk(path.join(p, name)));
    };
    walk(target);
}

/** Give a freshly written path to the PHP worker user so CMS uploads work. */
function fixOwnership(target) {
    if (process.getuid && process.getuid() !== 0) return;
    try { fs.lchownSync(target, cfg.php.fileUid, cfg.php.fileGid); } catch (_) { /* ignore */ }
}

function ensureRoots() {
    for (const dir of [SITES_DIR, DATA_DIR, PANEL_DIR]) {
        fs.mkdirSync(path.join(WWW, dir), { recursive: true });
    }
    const map = path.join(WWW, PANEL_DIR, 'domains.map');
    if (!fs.existsSync(map)) fs.writeFileSync(map, '# domain port\n');
}

function phpString(value) {
    return `'${String(value === null || value === undefined ? '' : value).replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

/** Private config the site reads through panel_config() (see prepend). */
function writeSiteConfig(record) {
    const dir = dataDir(record);
    fs.mkdirSync(dir, { recursive: true });
    const lines = [
        '<?php',
        '// Generated by the CS 1.6 panel. Regenerated automatically; do not edit.',
        'return [',
        `    'db' => [`,
        `        'host' => ${phpString(cfg.mysql.internalHost)},`,
        `        'port' => ${parseInt(cfg.mysql.internalPort, 10)},`,
        `        'name' => ${phpString(record.db_name)},`,
        `        'user' => ${phpString(record.db_username)},`,
        `        'pass' => ${phpString(record.db_password)},`,
        '    ],',
        `    'game' => [`,
        `        'name' => ${phpString(record.name)},`,
        `        'host' => ${phpString(cfg.gameServerHost)},`,
        `        'query_host' => ${phpString(`cs16-server-${portOf(record)}`)},`,
        `        'port' => ${portOf(record)},`,
        '    ],',
        `    'fastdl_url' => ${phpString(cfg.fastdlUrl(portOf(record)))},`,
        `    'site_url' => ${phpString(cfg.phpSiteUrl(portOf(record), record.php_domain))},`,
        '];',
        ''
    ];
    fs.writeFileSync(path.join(dir, 'config.php'), lines.join('\n'), { mode: 0o640 });
    for (const sub of ['sessions', 'tmp']) fs.mkdirSync(path.join(dir, sub), { recursive: true });
    chownTree(dir);
}

function copyDir(src, dest) {
    fs.mkdirSync(dest, { recursive: true });
    for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
        const from = path.join(src, entry.name);
        const to = path.join(dest, entry.name);
        if (entry.isDirectory()) copyDir(from, to);
        else if (entry.isFile()) fs.copyFileSync(from, to);
    }
}

function isEmptyDir(dir) {
    return !fs.existsSync(dir) || fs.readdirSync(dir).filter(n => n !== '.htaccess').length === 0;
}

/** Create the site skeleton (idempotent). New sites get the community template. */
async function ensureSite(record) {
    if (!record || !record.port) return null;
    ensureRoots();
    const dir = siteDir(record);
    const fresh = isEmptyDir(dir);
    fs.mkdirSync(dir, { recursive: true });
    if (fresh) installTemplateFiles('community', dir);
    writeSiteConfig(record);
    chownTree(dir);
    if (record.php_path !== `${SITES_DIR}/${portOf(record)}` || record.php_url !== cfg.phpSiteUrl(record.port, record.php_domain)) {
        await panelDb.updateServerContainer(record.container_id, {
            php_path: `${SITES_DIR}/${portOf(record)}`,
            php_url: cfg.phpSiteUrl(record.port, record.php_domain)
        });
    }
    return dir;
}

function removeSite(record) {
    if (!record || !record.port) return;
    for (const dir of [siteDir(record), dataDir(record)]) {
        if (fs.existsSync(dir)) fs.rmSync(dir, { recursive: true, force: true });
    }
}

function resetSite(record) {
    removeSite(record);
}

function installTemplateFiles(templateId, dir) {
    const template = TEMPLATES.find(t => t.id === templateId);
    if (!template) throw httpError(400, 'Bilinmeyen şablon.');
    const src = path.join(TEMPLATES_ROOT, template.id);
    if (!fs.existsSync(src)) throw httpError(500, 'Şablon dosyaları bulunamadı.');
    copyDir(src, dir);
}

async function installTemplate(record, templateId, { wipe = false } = {}) {
    const dir = siteDir(record);
    if (wipe && fs.existsSync(dir)) fs.rmSync(dir, { recursive: true, force: true });
    fs.mkdirSync(dir, { recursive: true });
    installTemplateFiles(templateId, dir);
    writeSiteConfig(record);
    chownTree(dir);
}

function siteUsage(record) {
    const dir = siteDir(record);
    let bytes = 0;
    let files = 0;
    const walk = p => {
        let entries;
        try { entries = fs.readdirSync(p, { withFileTypes: true }); } catch (_) { return; }
        for (const e of entries) {
            const full = path.join(p, e.name);
            if (e.isDirectory()) walk(full);
            else if (e.isFile()) {
                files++;
                try { bytes += fs.statSync(full).size; } catch (_) { /* raced */ }
            }
        }
    };
    if (fs.existsSync(dir)) walk(dir);
    return { bytes, files };
}

// ---------------------------------------------------------------------------
//  Custom domains
// ---------------------------------------------------------------------------

function normalizeDomain(value) {
    const domain = String(value || '').trim().toLowerCase().replace(/^https?:\/\//, '').replace(/\/.*$/, '');
    if (!domain) return null;
    if (domain.length > 190 || !/^(?=.{1,190}$)([a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}$/.test(domain)) {
        throw httpError(400, 'Geçerli bir alan adı girin (örn. www.sunucum.com).');
    }
    const panelHost = new URL(cfg.panelPublicUrl).hostname.toLowerCase();
    if (domain === panelHost) throw httpError(400, 'Panel alan adı bir siteye atanamaz.');
    return domain;
}

async function writeDomainMap() {
    ensureRoots();
    const [rows] = await panelDb.assertPool().query(
        'SELECT port, php_domain FROM panel_servers WHERE php_domain IS NOT NULL AND is_pool = 0 AND suspended = 0'
    );
    const lines = ['# Generated by the CS 1.6 panel: <domain> <port>'];
    rows.forEach(r => { lines.push(`${r.php_domain} ${r.port}`); });
    const target = path.join(WWW, PANEL_DIR, 'domains.map');
    const tmp = `${target}.tmp`;
    fs.writeFileSync(tmp, `${lines.join('\n')}\n`);
    fs.renameSync(tmp, target);
}

async function setDomain(record, domainInput) {
    const domain = normalizeDomain(domainInput);
    try {
        await panelDb.updateServerContainer(record.container_id, {
            php_domain: domain,
            php_url: cfg.phpSiteUrl(record.port, domain)
        });
    } catch (e) {
        if (e.code === 'ER_DUP_ENTRY') throw httpError(409, 'Bu alan adı başka bir sitede kullanılıyor.');
        throw e;
    }
    await writeDomainMap();
    const updated = await panelDb.getServerByContainerId(record.container_id);
    writeSiteConfig(updated);
    return updated;
}

function siteInfo(record) {
    const port = portOf(record);
    return {
        port,
        url: cfg.phpSiteUrl(port),
        domain: record.php_domain || null,
        domainUrl: record.php_domain ? cfg.phpSiteUrl(port, record.php_domain) : null,
        root: `${SITES_DIR}/${port}`,
        usage: siteUsage(record),
        database: {
            host: cfg.mysql.internalHost,
            port: cfg.mysql.internalPort,
            name: record.db_name,
            user: record.db_username
        },
        phpVersion: '8.2',
        templates: TEMPLATES
    };
}

module.exports = {
    TEMPLATES,
    SITES_DIR,
    ensureRoots,
    siteDir,
    dataDir,
    ensureSite,
    removeSite,
    resetSite,
    installTemplate,
    writeSiteConfig,
    writeDomainMap,
    setDomain,
    normalizeDomain,
    siteInfo,
    siteUsage,
    fixOwnership,
    chownTree,
    resolveInside
};
